---
#####
#
# @name MyINFRA.eu ~ Ansible RouterOS Role
# @version 2025.06-000.beta1
# @since 2025.06-000.beta1
#
# @copyright (c) 2025 (and beyond) - Dennis de Houx, All In One, One For The code
# @author Dennis de Houx <dennis@dehoux.be>
# @license https://creativecommons.org/licenses/by-nc-nd/4.0/deed.en CC BY-NC-ND 4.0
#
###
#
# Ansible role to manage address lists and firewall rules.
#
#####

- name: "Load: Address lists tasks"
  ansible.builtin.import_tasks: firewall_addr_lists.yml
  tags:
    - routeros_firewall_address_lists

- name: "Load: Firewall (IPv4) tasks"
  ansible.builtin.import_tasks: firewall_rules_ipv4.yml
  tags:
    - routeros_firewall_rules_ipv4
