---
#####
#
# @name One For The Code ~ Ansible RouterOS Role
# @version 2025.07-003
# @since 2025.07-000.beta1
#
# @copyright (c) 2025 (and beyond) - Dennis de Houx, All In One, One For The code
# @author Dennis de Houx <dennis@dehoux.be>
# @license https://creativecommons.org/licenses/by-nc-nd/4.0/deed.en CC BY-NC-ND 4.0
#
###
#
# Ansible taks to manage syslog settings
#
#####

- name: "LOGGING > Configure syslog settings"
  community.routeros.command:
    commands:
      - /system/logging remove [find where action=syslog]
      - /system/logging/action set [find where action=remote] remote={{ routeros_syslog_server | community.routeros.quote_argument_value }}
      - /system/logging/action remove [find where name=syslog]
      - /system/logging/action add name=syslog remote={{ routeros_syslog_server | community.routeros.quote_argument_value }} remote-port=514 syslog-facility=local7 syslog-severity=auto target=remote
      - /system logging add action=syslog disabled=no prefix={{ inventory_hostname }} topics=system,info
      - /system logging add action=syslog disabled=no prefix={{ inventory_hostname }} topics=warning
      - /system logging add action=syslog disabled=no prefix={{ inventory_hostname }} topics=critical
      - /system logging add action=syslog disabled=no prefix={{ inventory_hostname }} topics=error,!bgp,!ospf,!route
      - /system logging add action=syslog disabled=no prefix={{ inventory_hostname }}_routing topics=bgp,ospf,route
  register: syslog_logging_output
  when:
    - routeros_syslog_server is defined and routeros_syslog_server | length > 0

- name: "LOGGING > Add firewall rules"
  ansible.builtin.set_fact:
    routeros_firewall_rules: "{{ routeros_firewall_rules | default([]) + [{'type': 'ipv4', 'chain': chain, 'arguments': arguments, 'comment': 'Syslog Server ~ ' + comment}] }}"
  loop:
    #- { "chain": "input", "comment": "Inbound", "arguments": ['action=accept', 'src-address-list=syslog', 'port=514', 'protocol=udp'] }
    - {
        "chain": "forward",
        "comment": "Forward",
        "arguments":
          [
            "action=accept",
            "src-address-list=syslog",
            "port=514",
            "protocol=udp",
          ],
      }
    - {
        "chain": "forward",
        "comment": "Forward",
        "arguments":
          [
            "action=accept",
            "dst-address-list=syslog",
            "port=514",
            "protocol=udp",
          ],
      }
    - {
        "chain": "output",
        "comment": "Outbound",
        "arguments":
          [
            "action=accept",
            "dst-address-list=syslog",
            "port=514",
            "protocol=udp",
          ],
      }
  register: users_firewall_output
  vars:
    chain: "{{ item.chain }}"
    comment: "{{ item.comment }}"
    arguments: "{{ item.arguments }}"
  when:
    - routeros_syslog_server is defined and routeros_syslog_server | length > 0

- name: "LOGGING > Add firewall address-list"
  ansible.builtin.set_fact:
    routeros_address_list: "{{ routeros_address_list | default([]) + [{'list': 'syslog', 'address': [routeros_syslog_server], 'comment': 'Syslog Server - Automatic Added', 'enabled': true}] }}"
  register: syslog_firewall_adress_output
  when:
    - routeros_syslog_server is defined and routeros_syslog_server | length > 0

- name: "LOGGING > Show output"
  ansible.builtin.debug:
    msg:
      - "LOGGING       : {{ syslog_logging_output | default('') }}"
      - "FIREWALL      : {{ syslog_firewall_output | default('') }}"
      - "FIREWALL LIST : {{ syslog_firewall_address_output | default('') }}"
      - "FIREWALL RULES: {{ routeros_firewall_rules | default('') }}"
      - "ADDRESS LIST  : {{ routeros_address_list | default('') }}"
  tags:
    - routeros_show_output
