---
#####
#
# @name MyINFRA.eu ~ Ansible RouterOS Role
# @version 2025.07-003
# @since 2025.07-000.beta1
#
# @copyright (c) 2025 (and beyond) - Dennis de Houx, All In One, One For The code
# @author Dennis de Houx <dennis@dehoux.be>
# @license https://creativecommons.org/licenses/by-nc-nd/4.0/deed.en CC BY-NC-ND 4.0
#
###
#
# Ansible role for RouterOS
#
#####

- name: "Copyright & Version information"
  ansible.builtin.debug:
    msg:
      - "MyINFRA.eu ~ Ansible RouterOS Role"
      - "Version   : 2025.07-001"
      - "Copyright : (c) 2025 (and beyond) - Dennis de Houx, All In One, One For The code"
      - "Author    : Dennis de Houx <dennis@dehoux.be>"
      - "License   : https://creativecommons.org/licenses/by-nc-nd/4.0/deed.en CC BY-NC-ND 4.0"

- name: "Load: Gather facts tasks"
  ansible.builtin.import_tasks: gather.yml
  tags:
    - routeros_gather_facts

- name: "Enable Safe Mode"
  community.routeros.command:
    commands:
      - /safe-mode/take
  when: routeros_safe_mode is defined and routeros_safe_mode is true

- name: "Load: Banner tasks"
  ansible.builtin.import_tasks: banner.yml
  tags:
    - routeros_banner

- name: "Load: Logging tasks"
  ansible.builtin.import_tasks: logging.yml
  tags:
    - routeros_logging

- name: "Load: SNMP tasks"
  ansible.builtin.import_tasks: snmp.yml
  tags:
    - routeros_snmp

- name: "Load: Services tasks"
  ansible.builtin.import_tasks: services.yml
  tags:
    - routeros_services

- name: "Load: User management tasks"
  ansible.builtin.import_tasks: user-management.yml
  tags:
    - routeros_user_management

- name: "Load: Custom commands tasks"
  ansible.builtin.import_tasks: commands.yml
  tags:
    - routeros_custom_commands

- name: "Load: Firewall tasks"
  ansible.builtin.import_tasks: firewall.yml
  tags:
    - routeros_firewall

- name: "Release Safe Mode"
  community.routeros.command:
    commands:
      - /safe-mode/release
  when: routeros_safe_mode is defined and routeros_safe_mode is true
